apiVersion: v1
kind: Service
metadata: 
  name: santumemcache01
spec:
  ports:
    - port: 11211
      targetPort: santumemcache-port
      protocol: TCP
  selector:
    name: santumemcache
  type: ClusterIP