apiVersion: apps/v1
kind: Deployment
metadata:
  name: santumemcache
  labels: 
    app:  santumemcache
spec:
  selector:
    matchlabels:
      app: santumemcache
  replicas: 1
  template:
    metadata:
      matchlabels:
        app:  santumemcache

    spec:
      containes:
        - name: santumemcache
          image:  memcached
          ports:
            - name: santumemcache-port
              port: 11211