apiVersion: v1
kind: Service
metadata: 
  name: santuapptom-service
spec: 
  ports:
    - port: 80
      targetPort: santuapptom-port
      protocol: TCP
  selector:
    app:  santuapptom
  type: LoadBalancer
  
